repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        types: [python]

  - repo: local
    hooks:
      - id: rust-fmt
        name: rust fmt
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: rust-clippy
        name: rust clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: rust-test
        name: rust test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        stages: [manual]  # Optional: only run on manual pre-commit run 