[package]
name = "semisearch"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.80.0"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
ignore = "0.4"
# Phase 2: Enhanced Search dependencies
fuzzy-matcher = "0.3"
regex = "1.0"
edit-distance = "2.1"
# Phase 3: Text Processing dependencies
unicode-segmentation = "1.10"
thiserror = "1.0"
rayon = "1.7"
rustc-hash = "1.1"

[dev-dependencies]
tempfile = "3.0"
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"

# Version constraints for Rust 1.80.0 compatibility
[patch.crates-io]
half = "=2.4.1" 