[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y build-essential pkg-config"
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED"
]

OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1" 