[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED",
    "PKG_CONFIG_ALLOW_CROSS"
]

OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"
PKG_CONFIG_ALLOW_CROSS = "1"
