# cargo-deny configuration for security and license auditing
# Following the architecture plan's security requirements

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "CC0-1.0",                   # Creative Commons Zero (public domain)
    "MPL-2.0",                   # Mozilla Public License 2.0
    "CDLA-Permissive-2.0",      # Community Data License Agreement Permissive 2.0
]

# Confidence threshold for detecting a license from a license text.
confidence-threshold = 0.8

# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    # Each entry is the crate and version constraint, and its the license
    # { allow = ["OpenSSL"], name = "ring", version = "*" },
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Deny crates that are unmaintained
deny = [
    # Known problematic crates
    { name = "git2", version = "*" },     # Large dependency for simple file ops
]

# Skip certain crates when checking for duplicates
skip = [
    # Common transitive dependencies that often have version conflicts
    # { name = "windows-sys", version = "*" },
    # { name = "windows_x86_64_msvc", version = "*" },
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# A list of advisory IDs to ignore - including allowed unmaintained dependencies
ignore = [
    # paste crate unmaintained - transitive dependency from tokenizers, low risk for proc-macro
    "RUSTSEC-2024-0436",
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is
# not in the allow list is encountered
unknown-git = "warn"

# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of allowed Git repositories
allow-git = []
